version: 2.0

jobs:
    checkout_code:
        machine:
          enable: true

    working_directory: ~/project

    steps:
        - checkout

  bundle_dependencies:
      docker:
          - image: node:8-alpine

      working_directory: ~/project

      steps:
          - restore_cache:
              keys:
                  -node-modules

          - run: npm i

          - save_cache:
              key: node-modules
              paths:
                  - ~/node_modules

  test:
      docker:
          - image: node:8-alpine

      working_directory: ~/project

      environment:
          COVERALLS_SERVICE_JOB_ID: $CIRCLE_BUILD_NUM
          COVERALLS_GIT_COMMIT: $CIRLE_SHA1
          COVERALLS_PARALLEL: true

      steps:
          - run: npm test
          - run: if [ $CIRCLE_BRANCH = 'master' ]; then npm run coverage; fi

  build:
      docker:
          - image: node:8-alpine

      working_directory: ~/project

      steps:
          - run: npm run build

  deploy:
      docker:
          - image: node:8-alpine
      working_directory: ~/project
      steps:
          - run: echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
          - run: npm publish
          - run: npm logout

workflows:
    version: 2

    build_and_deploy:
        jobs:
            - checkout_code
            - bundle_dependencies:
                requires:
                    - checkout_code
            - test:
                requires:
                    - bundle_dependencies
            - build:
                requires:
                    - test
            - deploy:
                requires:
                    - build
                filters:
                    tags:
                        only: /[0-9]+(\.[0-9]+){2}(-(alpha|beta)[0-9]+)?/

                    branches:
                        ignore: /.*/
