version: 2.0

jobs:
    checkout:
        docker:
            - image: node:8

        steps:
            - checkout
            - run: ls -al
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - save_cache:
                key: project-{{ checksum ".circle-sha" }}
                paths:
                    - ~/project

    dependencies:
        docker:
            - image: node:8

        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - project-{{ checksum ".circle-sha" }}
            - restore_cache:
                keys:
                    - node_modules-{{ checksum "package.json" }}

            - run: ls -al
            - run: npm i

            - save_cache:
                key: node_modules-{{ checksum "package.json" }}
                paths:
                    - ~/project/node_modules

    test:
        docker:
            - image: node:8

        environment:
            COVERALLS_SERVICE_JOB_ID: $CIRCLE_BUILD_NUM
            COVERALLS_GIT_COMMIT: $CIRLE_SHA1
            COVERALLS_PARALLEL: true

        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - project-{{ checksum ".circle-sha" }}
            - restore_cache:
                keys:
                    - node_modules-{{ checksum "package.json" }}
            - run: npm test
            - run: if [ $CIRCLE_BRANCH = 'master' ]; then npm run coverage; fi

    build:
        docker:
            - image: node:8

        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - project-{{ checksum ".circle-sha" }}
            - restore_cache:
                keys:
                    - node_modules-{{ checksum "package.json" }}
            - run: npm run build

    deploy:
        docker:
            - image: node:8

        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - project-{{ checksum ".circle-sha" }}
            - restore_cache:
                keys:
                    - node_modules-{{ checksum "package.json" }}
            - run: echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
            - run: npm publish
            - run: npm logout

workflows:
    version: 2

    build_and_deploy:
        jobs:
            - checkout
            - dependencies:
                requires:
                    - checkout
            - test:
                requires:
                    - dependencies
            - build:
                requires:
                    - test
            - deploy:
                requires:
                    - build
                filters:
                    tags:
                        only: /[0-9]+(\.[0-9]+){2}(-(alpha|beta)[0-9]+)?/

                    branches:
                        ignore: /.*/
